#!/usr/bin/env node
// Builds integrations.html from tools/integrations/integrations.json.
//
//   node tools/integrations/build.mjs        (from the repo root)
//
// The top bar, footer and scroll script are copied from index.html as they
// are, so the shared site chrome stays the same on every page. Edit the JSON
// to add a card or change a status, then rebuild and commit both files.

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..', '..');
const data = JSON.parse(readFileSync(join(here, 'integrations.json'), 'utf8'));
const index = readFileSync(join(root, 'index.html'), 'utf8');

function cut(src, startRe, endTag, what) {
  const m = src.match(startRe);
  if (!m) throw new Error(`index.html: cannot find the ${what}`);
  const end = src.indexOf(endTag, m.index);
  if (end < 0) throw new Error(`index.html: ${what} is not closed`);
  return src.slice(m.index, end + endTag.length);
}
const topbar = cut(index, /<header class="topbar"/, '</header>', 'top bar');
const footer = cut(index, /<footer class="foot">/, '</footer>', 'footer');
// The same sticky-bar script the other content pages carry.
const script = `<script>(function(){var b=document.getElementById('topbar');function s(){b.classList.toggle('stuck',window.scrollY>8)}window.addEventListener('scroll',s,{passive:true});s();})();</script>`;

const esc = (s) => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

const banned = /—|&mdash;|&#8212;|&#x2014;/;
function checkProse(s, where) {
  if (banned.test(s)) throw new Error(`em dash in ${where}; reword it (see CLAUDE.md)`);
  return s;
}

function card(c, gid) {
  const st = data.statuses[c.status];
  if (!st) throw new Error(`${c.name}: unknown status "${c.status}"`);
  for (const k of ['name', 'line', 'setup', 'href']) if (!c[k]) throw new Error(`${c.name || gid}: missing ${k}`);
  checkProse(c.name + c.line, c.name);
  const setup = c.setupIsProse
    ? `<span class="su prose">${esc(checkProse(c.setup, c.name))}</span>`
    : `<code class="su">${esc(c.setup)}</code>`;
  const tick = st.tone === 'ok' ? '&#10003; ' : '';
  return `        <a class="ig-card${c.own ? ' own' : ''}" href="${esc(c.href)}"><span class="nm">${esc(c.name)}</span><span class="ln">${esc(c.line)}</span>${setup}<span class="st ${st.tone}">${tick}${esc(st.label)}</span></a>`;
}

function group(g) {
  checkProse(g.title + g.intro, g.id);
  return `    <section class="ig-sec" id="${esc(g.id)}" aria-labelledby="${esc(g.id)}-h">
      <h2 id="${esc(g.id)}-h">${esc(g.title)}</h2>
      <p>${esc(g.intro)}</p>
      <div class="ig-grid">
${g.cards.map((c) => card(c, g.id)).join('\n')}
      </div>
    </section>`;
}

const p = data.page;
checkProse(p.h1 + p.lede + p.description, 'page');

const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!-- Generated by tools/integrations/build.mjs from tools/integrations/integrations.json. Do not hand-edit. -->
  <title>${esc(p.title)}</title>
  <meta name="description" content="${esc(p.description)}">
  <link rel="canonical" href="${esc(p.url)}">
  <meta property="og:type" content="website">
  <meta property="og:site_name" content="AgentMesh">
  <meta property="og:title" content="${esc(p.title)}">
  <meta property="og:description" content="${esc(p.description)}">
  <meta property="og:url" content="${esc(p.url)}">
  <meta property="og:image" content="https://agentmesh.ai/brand/png/og-image.png">
  <meta property="og:image:width" content="1200">
  <meta property="og:image:height" content="630">
  <meta property="og:image:alt" content="AgentMesh">
  <meta name="twitter:card" content="summary_large_image">
  <link rel="icon" type="image/svg+xml" href="favicon.svg">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Bricolage+Grotesque:opsz,wdth,wght@12..96,75..100,400..700&family=Instrument+Sans:wdth,wght@75..100,400..700&family=Martian+Mono:wdth,wght@75..112.5,400..600&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="site.css">
  <style>
    /* Colours come from site.css tokens, so the page follows light and dark. */
    main p a:not([class]){color:var(--fg);text-decoration-color:var(--amber-line);text-decoration-thickness:1.5px;text-underline-offset:3px}
    main p a:not([class]):hover{text-decoration-thickness:3px}

    .lc-head{position:relative;padding-block:64px 40px}
    .lc-head::before{content:"";position:absolute;inset:0;z-index:-1;pointer-events:none;background-image:radial-gradient(var(--dot) 1.2px,transparent 1.4px);background-size:24px 24px;-webkit-mask-image:radial-gradient(60% 75% at 78% 40%,black,transparent 72%);mask-image:radial-gradient(60% 75% at 78% 40%,black,transparent 72%)}
    .lc-head h1{margin-top:22px;font-size:clamp(2.5rem,1.3rem + 3.3vw,4.15rem);line-height:.98;letter-spacing:-.04em;font-stretch:88%;max-width:18ch}
    .ig-lede{margin-top:22px;font-size:1.1rem;line-height:1.6;color:var(--muted);max-width:62ch}

    .ig-sec{padding-block:72px 16px;border-top:1px solid var(--line);display:flex;flex-direction:column;gap:14px}
    .ig-sec:first-of-type{border-top:0;padding-top:24px}
    .ig-sec h2{font-size:clamp(1.9rem,1.2rem + 2.1vw,2.85rem);line-height:1.05;letter-spacing:-.032em;font-stretch:90%}
    .ig-sec > p{color:var(--muted);font-size:1.08rem;max-width:60ch;margin-bottom:18px}
    .ig-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(260px,1fr));gap:16px;padding-bottom:56px}
    .ig-card{display:flex;flex-direction:column;gap:10px;min-width:0;padding:20px;border:1px solid var(--line);border-radius:18px;background:var(--surface);color:var(--fg);text-decoration:none;transition:transform .35s cubic-bezier(.2,.7,.2,1),border-color .35s,box-shadow .35s}
    .ig-card:hover{transform:translateY(-3px);border-color:var(--line-strong);box-shadow:var(--shadow)}
    .ig-card .nm{font-family:var(--display);font-size:1.28rem;font-weight:600;line-height:1.2;letter-spacing:-.015em}
    .ig-card .ln{flex:1;font-size:.95rem;line-height:1.5;color:var(--muted)}
    .ig-card .su{display:block;padding:8px 10px;border-radius:10px;background:var(--surface-2);font-family:var(--mono);font-stretch:87.5%;font-size:.7rem;line-height:1.5;color:var(--fg);overflow-wrap:break-word;hyphens:none}
    .ig-card .su.prose{font-family:inherit;font-stretch:normal;font-size:.85rem;color:var(--muted)}
    .ig-card .st{font-family:var(--mono);font-stretch:87.5%;font-size:.7rem;font-weight:500;letter-spacing:.02em;line-height:1.45;color:var(--faint)}
    .ig-card .st.ok{color:var(--mint-ink)}
    .ig-card.own{border-style:dashed;border-color:var(--line-strong);background:transparent}

    .lc-end{position:relative;overflow:hidden;border-top:1px solid var(--line);padding-block:104px}
    .lc-end::before{content:"";position:absolute;inset:0;pointer-events:none;background-image:radial-gradient(var(--dot) 1.2px,transparent 1.4px);background-size:24px 24px;-webkit-mask-image:radial-gradient(50% 90% at 85% 50%,black,transparent 72%);mask-image:radial-gradient(50% 90% at 85% 50%,black,transparent 72%)}
    .lc-end .wrap{position:relative;display:flex;flex-direction:column;align-items:flex-start;gap:18px}
    .lc-end h2{font-size:clamp(2rem,1.25rem + 2.5vw,3.25rem);line-height:1.04;letter-spacing:-.034em;font-stretch:90%}
    .lc-end p{color:var(--muted);font-size:1.08rem;max-width:56ch;margin-bottom:8px}

    @media (max-width:620px){
      .lc-head{padding-block:40px 28px}
      .ig-sec{padding-top:56px}
      .ig-grid{grid-template-columns:minmax(0,1fr);padding-bottom:40px}
      .lc-end{padding-block:72px}
    }
  </style>
</head>
<body>
  ${topbar}

  <main class="wrap">
    <div class="lc-head">
      <p class="kicker">${esc(p.kicker)}</p>
      <h1>${esc(p.h1)}</h1>
      <p class="ig-lede">${esc(p.lede)}</p>
    </div>

${data.groups.map(group).join('\n\n')}
  </main>

  <section class="lc-end">
    <div class="wrap">
      <h2>Bring yours.</h2>
      <p>AgentMesh is in beta. Join the waitlist, and we will write when a place opens.</p>
      <a class="btn btn-amber" href="waitlist.html?from=${esc(p.waitlistFrom)}">Join the waitlist<svg class="arr" viewBox="0 0 16 16" width="16" height="16" aria-hidden="true"><path d="M3 8h9M8.5 4.5 12 8l-3.5 3.5" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"/></svg></a>
    </div>
  </section>

  ${footer}
${script}
</body>
</html>
`;

writeFileSync(join(root, p.file), html);
console.log(`wrote ${p.file}: ${data.groups.length} groups, ${data.groups.reduce((n, g) => n + g.cards.length, 0)} cards`);
